name: AWS CI/CD Pipeline

on:
  push:
    branches: [ main ] # Jab aap code push karein ge tab ye chalega

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/gfdsa  # Yahan apne server wale folder ka sahi path likhein
            git pull origin main
            npm install
            pm2 restart all || pm2 start ecosystem.config.js